from typing import Any
from app.schemas.legal_research import LegalProvisionResponse, PotentialProvisionItem, StatuteMappingResponse


class StatuteRegistry:
    """
    Authoritative repository of verified Indian statutes and transition mappings.
    Grounded in official Gazette publications and Ministry of Law and Justice acts.
    """

    # Authoritative Old Law -> Current Law Transition Mappings
    STATUTE_MAPPINGS: dict[str, dict[str, Any]] = {
        # IPC -> BNS
        "IPC:420": {
            "old_act": "Indian Penal Code, 1860",
            "old_section": "Section 420",
            "old_title": "Cheating and dishonestly inducing delivery of property",
            "current_act": "Bharatiya Nyaya Sanhita, 2023 (BNS)",
            "current_section": "Section 318(4)",
            "current_title": "Cheating and dishonestly inducing delivery of property",
            "how_law_changed": "Section 420 IPC is repealed and replaced by Section 318(4) of Bharatiya Nyaya Sanhita, 2023 w.e.f. July 1, 2024. Preserves the substantive requirement of dishonest inducement at inception, punishable with imprisonment up to seven years and fine.",
            "key_differences": [
                "Replaces Section 420 IPC with Section 318(4) BNS.",
                "Substantive ingredients remain identical: deceitful inducement to deliver property or make/alter valuable security.",
                "Requires proof of dishonest intention existing at the inception of the transaction (Hridaya Ranjan Prasad Verma).",
            ],
            "is_repealed_or_replaced": True,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 850(E)",
        },
        "BNS:318": {
            "old_act": "Indian Penal Code, 1860",
            "old_section": "Section 420",
            "old_title": "Cheating and dishonestly inducing delivery of property",
            "current_act": "Bharatiya Nyaya Sanhita, 2023 (BNS)",
            "current_section": "Section 318",
            "current_title": "Cheating",
            "how_law_changed": "Replaces Sections 415-420 IPC w.e.f. July 1, 2024. Sub-section (1) defines cheating, Sub-section (2) provides simple punishment (up to 3 years), and Sub-section (4) penalizes cheating with delivery of property (up to 7 years).",
            "key_differences": [
                "Consolidates definition and penal consequences into Section 318 BNS.",
                "Section 318(4) corresponds directly to erstwhile Section 420 IPC.",
            ],
            "is_repealed_or_replaced": False,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 850(E)",
        },
        "IPC:406": {
            "old_act": "Indian Penal Code, 1860",
            "old_section": "Section 406",
            "old_title": "Punishment for criminal breach of trust",
            "current_act": "Bharatiya Nyaya Sanhita, 2023 (BNS)",
            "current_section": "Section 316",
            "current_title": "Criminal breach of trust",
            "how_law_changed": "Section 405/406 IPC replaced by Section 316 BNS w.e.f. July 1, 2024. Imprisonment up to five years or fine, or both.",
            "key_differences": [
                "Replaces Section 406 IPC with Section 316 BNS.",
                "Requires entrustment of property and subsequent dishonest misappropriation.",
            ],
            "is_repealed_or_replaced": True,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 850(E)",
        },
        "IPC:506": {
            "old_act": "Indian Penal Code, 1860",
            "old_section": "Section 506",
            "old_title": "Punishment for criminal intimidation",
            "current_act": "Bharatiya Nyaya Sanhita, 2023 (BNS)",
            "current_section": "Section 351(2) & 351(3)",
            "current_title": "Criminal intimidation",
            "how_law_changed": "Section 503 and 506 IPC consolidated into Section 351 BNS w.e.f. July 1, 2024. Sub-section (2) penalizes general intimidation (up to 2 years), Sub-section (3) penalizes threats to cause death, grievous hurt, or destruction of property (up to 7 years).",
            "key_differences": [
                "Integrated definition and punishment into Section 351 BNS.",
                "Distinguishes simple threat vs threat to kill or cause grievous bodily injury.",
            ],
            "is_repealed_or_replaced": True,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 850(E)",
        },
        "BNS:351": {
            "old_act": "Indian Penal Code, 1860",
            "old_section": "Section 506",
            "old_title": "Criminal Intimidation",
            "current_act": "Bharatiya Nyaya Sanhita, 2023 (BNS)",
            "current_section": "Section 351",
            "current_title": "Criminal Intimidation",
            "how_law_changed": "Replaces Section 503 and Section 506 IPC w.e.f. July 1, 2024.",
            "key_differences": [
                "Section 351(1) defines threat to cause injury to person, reputation, or property.",
                "Section 351(2) prescribes punishment up to 2 years.",
                "Section 351(3) prescribes punishment up to 7 years for death/grievous hurt threats.",
            ],
            "is_repealed_or_replaced": False,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 850(E)",
        },
        "IPC:441": {
            "old_act": "Indian Penal Code, 1860",
            "old_section": "Section 441 & 447",
            "old_title": "Criminal trespass and punishment",
            "current_act": "Bharatiya Nyaya Sanhita, 2023 (BNS)",
            "current_section": "Section 329",
            "current_title": "Criminal trespass and house-trespass",
            "how_law_changed": "Replaces Section 441 and 447 IPC w.e.f. July 1, 2024. Entering or remaining upon property with intent to commit an offence, intimidate, insult, or annoy.",
            "key_differences": [
                "Consolidates criminal trespass definitions under Section 329 BNS.",
                "Punishment up to 3 months imprisonment or fine up to five thousand rupees.",
            ],
            "is_repealed_or_replaced": True,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 850(E)",
        },
        "BNS:329": {
            "old_act": "Indian Penal Code, 1860",
            "old_section": "Section 441 & 447",
            "old_title": "Criminal trespass",
            "current_act": "Bharatiya Nyaya Sanhita, 2023 (BNS)",
            "current_section": "Section 329",
            "current_title": "Criminal trespass and house-trespass",
            "how_law_changed": "Current law governing criminal trespass and unlawful possession w.e.f. July 1, 2024.",
            "key_differences": [
                "Replaces Sections 441, 447, and 448 of IPC.",
            ],
            "is_repealed_or_replaced": False,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 850(E)",
        },
        "IPC:299": {
            "old_act": "Indian Penal Code, 1860",
            "old_section": "Section 299",
            "old_title": "Culpable homicide",
            "current_act": "Bharatiya Nyaya Sanhita, 2023 (BNS)",
            "current_section": "Section 100",
            "current_title": "Culpable homicide",
            "how_law_changed": "Replaced by Section 100 BNS w.e.f. July 1, 2024. Genera of culpable homicide preceding the species of murder.",
            "key_differences": [
                "Replaced Section 299 IPC with Section 100 BNS.",
                "Punishment codified under Section 105 BNS (previously Section 304 IPC).",
            ],
            "is_repealed_or_replaced": True,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 850(E)",
        },
        "BNS:100": {
            "old_act": "Indian Penal Code, 1860",
            "old_section": "Section 299",
            "old_title": "Culpable homicide",
            "current_act": "Bharatiya Nyaya Sanhita, 2023 (BNS)",
            "current_section": "Section 100",
            "current_title": "Culpable homicide",
            "how_law_changed": "Current governing provision for culpable homicide w.e.f. July 1, 2024.",
            "key_differences": [
                "Replaces Section 299 IPC.",
            ],
            "is_repealed_or_replaced": False,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 850(E)",
        },
        "IPC:300": {
            "old_act": "Indian Penal Code, 1860",
            "old_section": "Section 300",
            "old_title": "Murder",
            "current_act": "Bharatiya Nyaya Sanhita, 2023 (BNS)",
            "current_section": "Section 101",
            "current_title": "Murder",
            "how_law_changed": "IPC 1860 is repealed and replaced by Bharatiya Nyaya Sanhita, 2023 w.e.f. July 1, 2024. The substantive definition of murder is codified under Section 101 BNS, and punishment under Section 103 BNS. Notably, Section 103(2) introduces a distinct aggravated provision punishing mob lynching or group-based murder.",
            "key_differences": [
                "Definition of murder codified under Section 101 BNS (previously Section 300 IPC).",
                "Punishment for murder codified under Section 103 BNS (previously Section 302 IPC).",
                "Section 103(2) BNS introduces specific statutory punishment (death or life imprisonment) for murder committed by a group of five or more persons acting in concert on grounds of race, caste, sex, community, place of birth, language, religion, or personal belief (Mob Lynching).",
                "Archaic colonial language modernized throughout the illustrations.",
            ],
            "is_repealed_or_replaced": True,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 850(E)",
        },
        "IPC:302": {
            "old_act": "Indian Penal Code, 1860",
            "old_section": "Section 302",
            "old_title": "Punishment for Murder",
            "current_act": "Bharatiya Nyaya Sanhita, 2023 (BNS)",
            "current_section": "Section 103",
            "current_title": "Punishment for Murder",
            "how_law_changed": "Replaced by Section 103 of Bharatiya Nyaya Sanhita, 2023 w.e.f. July 1, 2024. Sub-section (1) provides death or imprisonment for life and fine; sub-section (2) penalizes group murder / mob lynching.",
            "key_differences": [
                "Replaced Section 302 IPC with Section 103 BNS.",
                "Section 103(1) retains death or life imprisonment plus mandatory fine.",
                "Section 103(2) adds dedicated penalty for mob lynching.",
            ],
            "is_repealed_or_replaced": True,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 850(E)",
        },
        "IPC:34": {
            "old_act": "Indian Penal Code, 1860",
            "old_section": "Section 34",
            "old_title": "Acts done by several persons in furtherance of common intention",
            "current_act": "Bharatiya Nyaya Sanhita, 2023 (BNS)",
            "current_section": "Section 3(5)",
            "current_title": "Joint Liability / Common Intention",
            "how_law_changed": "The joint liability principle previously contained in Section 34 of the IPC has been restructured and consolidated into Chapter II (General Explanations) under Section 3, Sub-section (5) of BNS 2023, effective July 1, 2024.",
            "key_differences": [
                "Relocated from stand-alone Section 34 IPC to Section 3(5) BNS under General Explanations.",
                "Substantive principle of vicarious criminal liability for acts done in furtherance of common intention remains identical in scope.",
                "Reinforces established jurisprudence (Barendra Kumar Ghosh & Mahbub Shah) requiring prior meeting of minds and active participation.",
            ],
            "is_repealed_or_replaced": True,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 850(E)",
        },
        "BNS:101": {
            "old_act": "Indian Penal Code, 1860",
            "old_section": "Section 300",
            "old_title": "Murder",
            "current_act": "Bharatiya Nyaya Sanhita, 2023 (BNS)",
            "current_section": "Section 101",
            "current_title": "Murder",
            "how_law_changed": "Current governing law replacing Section 300 of the Indian Penal Code w.e.f. July 1, 2024. Preserves four culpable homicide clauses and five mitigating exceptions.",
            "key_differences": [
                "Replaces Section 300 of Indian Penal Code, 1860.",
                "Accompanied by Section 103 BNS (Punishment for Murder).",
                "Applies to offences committed on or after July 1, 2024.",
            ],
            "is_repealed_or_replaced": False,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 850(E)",
        },
        "BNS:103": {
            "old_act": "Indian Penal Code, 1860",
            "old_section": "Section 302",
            "old_title": "Punishment for Murder",
            "current_act": "Bharatiya Nyaya Sanhita, 2023 (BNS)",
            "current_section": "Section 103",
            "current_title": "Punishment for Murder",
            "how_law_changed": "Replaces Section 302 IPC w.e.f. July 1, 2024. Subsection (2) explicitly penalizes mob lynching.",
            "key_differences": [
                "Subsection (1): Death or imprisonment for life and fine.",
                "Subsection (2): Murder committed by 5+ persons on specified discriminatory grounds punished with death or life imprisonment.",
            ],
            "is_repealed_or_replaced": False,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 850(E)",
        },
        "BNS:3(5)": {
            "old_act": "Indian Penal Code, 1860",
            "old_section": "Section 34",
            "old_title": "Acts done by several persons in furtherance of common intention",
            "current_act": "Bharatiya Nyaya Sanhita, 2023 (BNS)",
            "current_section": "Section 3(5)",
            "current_title": "Joint Liability / Common Intention",
            "how_law_changed": "Replaces Section 34 of the Indian Penal Code, 1860 w.e.f. July 1, 2024.",
            "key_differences": [
                "Integrated into General Explanations Chapter II Section 3(5).",
                "Substantive rule unchanged: each participant liable as if the act were done by him alone.",
            ],
            "is_repealed_or_replaced": False,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 850(E)",
        },

        # CrPC -> BNSS
        "CRPC:438": {
            "old_act": "Code of Criminal Procedure, 1973",
            "old_section": "Section 438",
            "old_title": "Direction for grant of bail to person apprehending arrest (Anticipatory Bail)",
            "current_act": "Bharatiya Nagarik Suraksha Sanhita, 2023 (BNSS)",
            "current_section": "Section 482",
            "current_title": "Direction for grant of bail to person apprehending arrest",
            "how_law_changed": "Section 438 CrPC is repealed and replaced by Section 482 BNSS w.e.f. July 1, 2024. High Courts and Sessions Courts retain concurrent powers to grant pre-arrest anticipatory bail.",
            "key_differences": [
                "Replaced Section 438 CrPC with Section 482 BNSS.",
                "Clarifies procedural factors including presence of applicant during final hearing and condition imposing powers.",
                "Constitution Bench jurisprudence (Sushila Aggarwal) holding anticipatory bail does not automatically lapse upon chargesheet filing continues to guide Section 482 BNSS interpretation.",
            ],
            "is_repealed_or_replaced": True,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 851(E)",
        },
        "BNSS:482": {
            "old_act": "Code of Criminal Procedure, 1973",
            "old_section": "Section 438",
            "old_title": "Anticipatory Bail",
            "current_act": "Bharatiya Nagarik Suraksha Sanhita, 2023 (BNSS)",
            "current_section": "Section 482",
            "current_title": "Direction for grant of bail to person apprehending arrest",
            "how_law_changed": "Current statutory framework for anticipatory bail replacing Section 438 CrPC w.e.f. July 1, 2024.",
            "key_differences": [
                "Jurisdiction vested concurrently in High Court and Court of Session.",
                "Mandatory conditions regarding cooperation with investigation and non-tampering of witnesses.",
            ],
            "is_repealed_or_replaced": False,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 851(E)",
        },
        "CRPC:154": {
            "old_act": "Code of Criminal Procedure, 1973",
            "old_section": "Section 154",
            "old_title": "Information in cognizable cases (FIR)",
            "current_act": "Bharatiya Nagarik Suraksha Sanhita, 2023 (BNSS)",
            "current_section": "Section 173",
            "current_title": "Information in cognizable cases (Zero FIR / e-FIR)",
            "how_law_changed": "Replaces Section 154 CrPC w.e.f. July 1, 2024. Formalizes Zero FIR registration regardless of jurisdiction and enables electronic information (e-FIR).",
            "key_differences": [
                "Mandatory Zero FIR: Police station must register FIR irrespective of territorial jurisdiction.",
                "Statutory recognition of e-FIR with signature requirement within three days.",
                "Preliminary inquiry permitted in offences punishable between 3 to 7 years with prior DSP permission.",
            ],
            "is_repealed_or_replaced": True,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 851(E)",
        },

        # IEA -> BSA
        "IEA:65B": {
            "old_act": "Indian Evidence Act, 1872",
            "old_section": "Section 65B",
            "old_title": "Admissibility of electronic records",
            "current_act": "Bharatiya Sakshya Adhiniyam, 2023 (BSA)",
            "current_section": "Section 61 / Section 63",
            "current_title": "Admissibility of Electronic Records and Certificate Requirements",
            "how_law_changed": "Section 65B of Indian Evidence Act, 1872 is replaced by Sections 61 and 63 of Bharatiya Sakshya Adhiniyam, 2023 w.e.f. July 1, 2024. Modernizes admissibility standards for cloud computing, distributed databases, smartphones, and digital media.",
            "key_differences": [
                "Section 61 BSA establishes electronic records shall have same legal status as printed paper documents.",
                "Section 63 BSA prescribes the certificate format, incorporating hash values and cryptographic integrity.",
                "Permits certificate to be signed by person in official charge of system or an expert.",
            ],
            "is_repealed_or_replaced": True,
            "effective_date": "July 1, 2024",
            "statutory_authority": "Ministry of Law and Justice, Gazette Notification S.O. 852(E)",
        },
    }

    # Authoritative Legal Provisions Database
    PROVISIONS: dict[str, LegalProvisionResponse] = {
        "IPC:300": LegalProvisionResponse(
            act_title="Indian Penal Code, 1860",
            act_code="IPC",
            enactment_year=1860,
            jurisdiction="Central",
            section_number="Section 300",
            section_title="Murder",
            what_it_means="Except in the cases specifically excepted by statute, culpable homicide is murder if the act by which the death is caused is done with the intention of causing death, or causing bodily injury sufficient in the ordinary course of nature to cause death.",
            legal_interpretation="Murder under Section 300 is the aggravated form of culpable homicide (Section 299). It requires either subjective intention to cause death, or subjective intention to inflict a bodily injury which is objectively assessed as sufficient in the ordinary course of nature to cause death (Virsa Singh v. State of Punjab).",
            ingredients=[
                "Clause 1: Intention of causing death.",
                "Clause 2: Intention of causing such bodily injury as the offender knows to be likely to cause the death of the person to whom the harm is caused.",
                "Clause 3: Intention of causing bodily injury to any person, and the bodily injury intended to be inflicted is sufficient in the ordinary course of nature to cause death.",
                "Clause 4: Knowledge that the act is so imminently dangerous that it must in all probability cause death or bodily injury likely to cause death, without any lawful excuse.",
                "Exception 1: Grave and sudden provocation (subject to Nanavati tests).",
                "Exception 2: Right of private defence exceeded in good faith.",
                "Exception 3: Public servant acting in good faith for public justice.",
                "Exception 4: Sudden fight in heat of passion upon sudden quarrel without premeditation.",
                "Exception 5: Death caused with consent of deceased being above 18 years of age.",
            ],
            punishment_or_remedy="Punishable under Section 302 IPC (Death or imprisonment for life, and fine). Replaced by Section 103 BNS.",
            related_provisions=["Section 299 IPC", "Section 302 IPC", "Section 304 IPC", "Section 101 BNS", "Section 103 BNS"],
            status="Repealed by Bharatiya Nyaya Sanhita, 2023 (Applies to offences committed prior to July 1, 2024)",
            effective_date="October 6, 1860 (Repealed July 1, 2024)",
        ),
        "IPC:34": LegalProvisionResponse(
            act_title="Indian Penal Code, 1860",
            act_code="IPC",
            enactment_year=1860,
            jurisdiction="Central",
            section_number="Section 34",
            section_title="Acts done by several persons in furtherance of common intention",
            what_it_means="When a criminal act is done by several persons in furtherance of the common intention of all, each of such persons is liable for that act in the same manner as if it were done by him alone.",
            legal_interpretation="Section 34 is a rule of evidence and liability, not a substantive penal offence in itself. It establishes joint or vicarious liability based on the principle that the act of one is the act of all when done in furtherance of a shared prior concert or pre-arranged plan (Barendra Kumar Ghosh; Mahbub Shah).",
            ingredients=[
                "1. Commission of a criminal act by two or more persons.",
                "2. Common intention: Pre-arranged plan, prior meeting of minds, or intention developed on the spot shared by all participants.",
                "3. Participation: Physical presence or active participation in the preparatory or executing acts.",
            ],
            punishment_or_remedy="Joint penal liability matching the substantive offence committed.",
            related_provisions=["Section 149 IPC (Unlawful Assembly)", "Section 120A/120B IPC (Conspiracy)", "Section 3(5) BNS"],
            status="Repealed by BNS 2023 (replaced under Section 3(5) BNS)",
            effective_date="October 6, 1860 (Repealed July 1, 2024)",
        ),
        "BNS:101": LegalProvisionResponse(
            act_title="Bharatiya Nyaya Sanhita, 2023",
            act_code="BNS",
            enactment_year=2023,
            jurisdiction="Central",
            section_number="Section 101",
            section_title="Murder",
            what_it_means="Except in the cases excepted by law, culpable homicide is murder if the act by which the death is caused is done with the intention of causing death or bodily injury known or sufficient in the ordinary course of nature to cause death.",
            legal_interpretation="Governing provision for murder under Indian criminal law effective July 1, 2024, replacing Section 300 IPC. Preserves the four constituent clauses of mental culpability and the five mitigating exceptions.",
            ingredients=[
                "1. Act done with intention of causing death.",
                "2. Act done with knowledge that bodily injury caused is likely to cause death of that particular person.",
                "3. Intended bodily injury is sufficient in ordinary course of nature to cause death.",
                "4. Act is so imminently dangerous that in all probability it causes death.",
                "Five statutory exceptions: Provocation, Private Defence, Public Servant, Sudden Fight, Adult Consent.",
            ],
            punishment_or_remedy="Punishable under Section 103 BNS (Death or imprisonment for life, and fine).",
            related_provisions=["Section 100 BNS", "Section 103 BNS", "Section 104 BNS", "Section 105 BNS", "Section 300 IPC"],
            status="In Force",
            effective_date="July 1, 2024",
        ),
        "BNS:103": LegalProvisionResponse(
            act_title="Bharatiya Nyaya Sanhita, 2023",
            act_code="BNS",
            enactment_year=2023,
            jurisdiction="Central",
            section_number="Section 103",
            section_title="Punishment for Murder",
            what_it_means="Defines the statutory punishment for murder, including capital punishment or imprisonment for life, and establishes an explicit aggravated provision for mob lynching and group murders.",
            legal_interpretation="Replaces Section 302 IPC. Sub-section (1) provides general punishment for murder. Sub-section (2) is a historic legislative addition creating joint liability and severe punishment for murders committed by mobs of five or more persons on protected grounds.",
            ingredients=[
                "Subsection (1): General punishment - Death or imprisonment for life, and liability to fine.",
                "Subsection (2): Mob Lynching - Group of five or more persons acting in concert committing murder on grounds of race, caste, community, sex, place of birth, language, religion, or personal belief.",
            ],
            punishment_or_remedy="Death or imprisonment for life, and fine.",
            related_provisions=["Section 101 BNS", "Section 102 BNS", "Section 302 IPC"],
            status="In Force",
            effective_date="July 1, 2024",
        ),
        "BNS:3(5)": LegalProvisionResponse(
            act_title="Bharatiya Nyaya Sanhita, 2023",
            act_code="BNS",
            enactment_year=2023,
            jurisdiction="Central",
            section_number="Section 3(5)",
            section_title="Common Intention and Joint Liability",
            what_it_means="When a criminal act is done by several persons in furtherance of the common intention of all, each of such persons is liable for that act in the same manner as if it were done by him alone.",
            legal_interpretation="Direct statutory replacement for Section 34 of the Indian Penal Code, codified in Chapter II of BNS 2023.",
            ingredients=[
                "1. Plurality of persons acting together.",
                "2. Pre-existing or contemporaneous common intention.",
                "3. Participation in furtherance of that common intention.",
            ],
            punishment_or_remedy="Equal liability for the resulting substantive offence.",
            related_provisions=["Section 189 BNS (Unlawful Assembly)", "Section 61 BNS (Criminal Conspiracy)", "Section 34 IPC"],
            status="In Force",
            effective_date="July 1, 2024",
        ),
        "NI ACT:138": LegalProvisionResponse(
            act_title="Negotiable Instruments Act, 1881",
            act_code="NI Act",
            enactment_year=1881,
            jurisdiction="Central",
            section_number="Section 138",
            section_title="Dishonour of cheque for insufficiency, etc., of funds in the account",
            what_it_means="Where any cheque drawn by a person on an account maintained by him with a banker for payment of any amount of money to another person from out of that account for the discharge, in whole or in part, of any debt or other liability, is returned by the bank unpaid, either because of the amount of money standing to the credit of that account is insufficient or exceeds arrangement, such person shall be deemed to have committed an offence.",
            legal_interpretation="Section 138 is a special penal provision designed to enhance the credibility of commercial transactions and negotiable instruments. It creates statutory deemed criminal liability for a civil debt default, subject to rigorous compliance with procedural conditions precedent.",
            ingredients=[
                "1. Drawing of cheque on account maintained by drawer for discharge of legally enforceable debt or liability.",
                "2. Presentation of cheque to bank within validity period (3 months).",
                "3. Return of cheque unpaid due to insufficiency of funds or arrangement exceeded.",
                "4. Statutory Demand Notice: Written notice demanding payment sent to drawer within 30 days of receiving memo of dishonour from bank.",
                "5. Failure to pay: Drawer fails to make payment of said amount within 15 days of receipt of notice.",
                "6. Cause of action: Arises on 16th day; complaint under Section 142 must be filed within 1 month.",
            ],
            punishment_or_remedy="Imprisonment for a term which may extend to two years, or with fine which may extend to twice the amount of the cheque, or with both.",
            related_provisions=["Section 139 NI Act (Presumption)", "Section 141 NI Act (Company Offences)", "Section 142 NI Act (Cognizance & Jurisdiction)", "Section 143A NI Act (Interim Compensation)"],
            status="In Force (Amended by Act 26 of 2015 and Act 20 of 2018)",
            effective_date="December 9, 1881",
        ),
        "ARBITRATION ACT:11": LegalProvisionResponse(
            act_title="Arbitration and Conciliation Act, 1996",
            act_code="Arbitration Act",
            enactment_year=1996,
            jurisdiction="Central",
            section_number="Section 11",
            section_title="Appointment of Arbitrators",
            what_it_means="Provides statutory mechanism for judicial appointment of an arbitrator by the Supreme Court (for international commercial arbitration) or High Court (for domestic arbitration) upon failure of the contractual appointment procedure between parties.",
            legal_interpretation="Section 11(6A) restricts judicial review strictly to the prima facie examination of the existence of an arbitration agreement (Vidya Drolia; In Re: Stamp Act). Courts do not examine arbitrability on merits at the threshold stage.",
            ingredients=[
                "1. Existence of a valid written arbitration agreement between parties.",
                "2. Invocation of arbitration notice under Section 21.",
                "3. Failure of agreed appointment mechanism or 30 days lapse without consensus.",
                "4. Application to the competent High Court or Supreme Court.",
            ],
            punishment_or_remedy="Judicial appointment of independent arbitrator / arbitral tribunal referral.",
            related_provisions=["Section 8", "Section 9", "Section 16", "Section 34", "Section 37"],
            status="In Force",
            effective_date="August 22, 1996",
        ),
        "CRPC:438": LegalProvisionResponse(
            act_title="Code of Criminal Procedure, 1973",
            act_code="CrPC",
            enactment_year=1973,
            jurisdiction="Central",
            section_number="Section 438",
            section_title="Direction for grant of bail to person apprehending arrest (Anticipatory Bail)",
            what_it_means="Where any person has reason to believe that he may be arrested on an accusation of having committed a non-bailable offence, he may apply to the High Court or the Court of Session for a direction under this section; and that Court may, if it thinks fit, direct that in the event of such arrest, he shall be released on bail.",
            legal_interpretation="Special judicial discretion to safeguard personal liberty against unwarranted or malicious arrest (Gurbaksh Singh Sibbia; Sushila Aggarwal). Anticipatory bail is not ordinary bail; it operates prior to physical arrest.",
            ingredients=[
                "1. Reasonable apprehension of arrest on accusation of non-bailable offence.",
                "2. Application before Court of Session or High Court.",
                "3. Considerations: Nature and gravity of accusation, criminal antecedents, possibility of fleeing justice.",
                "4. Imposition of conditions: Available for interrogation, no tampering, no leaving country without permission.",
            ],
            punishment_or_remedy="Pre-arrest protection; direction to release on bail in event of arrest.",
            related_provisions=["Section 437 CrPC", "Section 439 CrPC", "Section 482 BNSS", "Article 21 Constitution of India"],
            status="Repealed by BNSS 2023 (Replaced by Section 482 BNSS)",
            effective_date="April 1, 1974 (Repealed July 1, 2024)",
        ),
        "BNSS:482": LegalProvisionResponse(
            act_title="Bharatiya Nagarik Suraksha Sanhita, 2023",
            act_code="BNSS",
            enactment_year=2023,
            jurisdiction="Central",
            section_number="Section 482",
            section_title="Direction for grant of bail to person apprehending arrest",
            what_it_means="Governing provision under BNSS 2023 empowering High Courts and Courts of Session to grant anticipatory bail to persons apprehending arrest in non-bailable offences.",
            legal_interpretation="Direct statutory successor to Section 438 CrPC w.e.f. July 1, 2024.",
            ingredients=[
                "1. Apprehension of arrest in non-bailable offence.",
                "2. Concurrent jurisdiction in High Court and Sessions Court.",
                "3. Conditions to ensure compliance with police investigation.",
            ],
            punishment_or_remedy="Pre-arrest bail protection order.",
            related_provisions=["Section 480 BNSS", "Section 483 BNSS", "Section 438 CrPC"],
            status="In Force",
            effective_date="July 1, 2024",
        ),
        "CONTRACT ACT:73": LegalProvisionResponse(
            act_title="Indian Contract Act, 1872",
            act_code="Contract Act",
            enactment_year=1872,
            jurisdiction="Central",
            section_number="Section 73",
            section_title="Compensation for loss or damage caused by breach of contract",
            what_it_means="When a contract has been broken, the party who suffers by such breach is entitled to receive, from the party who has broken the contract, compensation for any loss or damage caused to him thereby, which naturally arose in the usual course of things from such breach, or which the parties knew, when they made the contract, to be likely to result from the breach of it.",
            legal_interpretation="Codifies the common law rule in Hadley v. Baxendale. Compensation is compensatory, not penal; remote and indirect damages are strictly excluded. The plaintiff has a duty to mitigate losses.",
            ingredients=[
                "1. Existence of valid binding contract.",
                "2. Breach committed by defendant.",
                "3. Actual loss or damage suffered as a direct and natural consequence.",
                "4. Loss was in contemplation of parties at time of contracting.",
            ],
            punishment_or_remedy="Award of damages / financial restitution.",
            related_provisions=["Section 74 Contract Act", "Section 75 Contract Act"],
            status="In Force",
            effective_date="September 1, 1872",
        ),
        "CONTRACT ACT:74": LegalProvisionResponse(
            act_title="Indian Contract Act, 1872",
            act_code="Contract Act",
            enactment_year=1872,
            jurisdiction="Central",
            section_number="Section 74",
            section_title="Compensation for breach of contract where penalty stipulated for",
            what_it_means="When a contract has been broken, if a sum is named in the contract as the amount to be paid in case of such breach, or if the contract contains any other stipulation by way of penalty, the party complaining of the breach is entitled, whether or not actual damage or loss is proved to have been caused thereby, to receive from the party who has broken the contract reasonable compensation not exceeding the amount so named or, as the case may be, the penalty stipulated for.",
            legal_interpretation="Definitive locus classicus on liquidated damages and earnest money forfeiture (Kailash Nath Associates v. DDA; Fateh Chand). Proof of actual legal injury is sine qua non; court awards only reasonable compensation not exceeding the ceiling stipulated.",
            ingredients=[
                "1. Contractual stipulation naming liquidated damages or penalty clause.",
                "2. Breach of contract.",
                "3. Assessment of reasonable compensation up to the stipulated ceiling.",
                "4. Where loss can be calculated, it must be proved; where loss cannot be calculated, genuine pre-estimate may be awarded.",
            ],
            punishment_or_remedy="Reasonable compensation; prevention of unjust forfeiture of deposits.",
            related_provisions=["Section 73 Contract Act", "Section 75 Contract Act"],
            status="In Force",
            effective_date="September 1, 1872",
        ),
        "CPC:9": LegalProvisionResponse(
            act_title="Code of Civil Procedure, 1908",
            act_code="CPC",
            enactment_year=1908,
            jurisdiction="Central",
            section_number="Section 9",
            section_title="Courts to try all civil suits unless barred",
            what_it_means="The Courts shall have jurisdiction to try all suits of a civil nature excepting suits of which their cognizance is either expressly or impliedly barred.",
            legal_interpretation="Constitutional charter of civil court jurisdiction in India. Civil courts have plenary inherent jurisdiction. Exclusion of civil court jurisdiction is never readily inferred and must be strictly proved (Dhulabhai v. State of MP).",
            ingredients=[
                "1. Suit must be of a civil nature (dispute regarding property, status, office, or contract).",
                "2. No express statutory bar (e.g. Section 430 Companies Act, Section 34 SARFAESI).",
                "3. No implied bar (statute creating exclusive machinery with finality provisions).",
            ],
            punishment_or_remedy="Maintainability of original civil suit.",
            related_provisions=["Order VII Rule 11 CPC", "Section 11 CPC (Res Judicata)"],
            status="In Force",
            effective_date="January 1, 1909",
        ),
        "COI:21": LegalProvisionResponse(
            act_title="Constitution of India, 1950",
            act_code="COI",
            enactment_year=1950,
            jurisdiction="Central",
            section_number="Article 21",
            section_title="Protection of Life and Personal Liberty",
            what_it_means="No person shall be deprived of his life or personal liberty except according to procedure established by law.",
            legal_interpretation="Expansive fundamental right. Procedure must be just, fair and reasonable (Maneka Gandhi). Encompasses privacy (Puttaswamy), clean environment (Subhash Kumar), speedy trial, and legal aid.",
            ingredients=[
                "1. Applicable to both citizens and non-citizens.",
                "2. Deprivation only by valid law.",
                "3. Three-fold test of state interference: Legality, Legitimate State Aim, Proportionality.",
            ],
            punishment_or_remedy="Writ remedies under Article 32 (Supreme Court) and Article 226 (High Courts).",
            related_provisions=["Article 14", "Article 19", "Article 32", "Article 226"],
            status="In Force",
            effective_date="January 26, 1950",
        ),
        "IPC:420": LegalProvisionResponse(
            act_title="Indian Penal Code, 1860",
            act_code="IPC",
            enactment_year=1860,
            jurisdiction="Central",
            section_number="Section 420",
            section_title="Cheating and dishonestly inducing delivery of property",
            what_it_means="Whoever cheats and thereby dishonestly induces the person deceived to deliver any property to any person, or to make, alter or destroy the whole or any part of a valuable security, is punishable under this section.",
            legal_interpretation="Distinction between mere breach of contract and cheating depends on whether fraudulent/dishonest intention existed at the time of the inducement or inception of the transaction (Hridaya Ranjan Prasad Verma v. State of Bihar).",
            ingredients=[
                "1. Deception of any person by fraudulent or dishonest representation.",
                "2. Dishonest inducement to deliver any property, or make/alter a valuable security.",
                "3. Mens Rea: Dishonest intention must exist at the inception of the transaction.",
            ],
            punishment_or_remedy="Imprisonment for a term which may extend to seven years, and liability to fine. Replaced by Section 318(4) BNS.",
            related_provisions=["Section 415 IPC", "Section 406 IPC", "Section 465 IPC", "Section 318 BNS"],
            status="Repealed by Bharatiya Nyaya Sanhita, 2023 (Applies to pre-July 1, 2024 offences)",
            effective_date="October 6, 1860 (Repealed July 1, 2024)",
        ),
        "BNS:318": LegalProvisionResponse(
            act_title="Bharatiya Nyaya Sanhita, 2023",
            act_code="BNS",
            enactment_year=2023,
            jurisdiction="Central",
            section_number="Section 318",
            section_title="Cheating",
            what_it_means="Whoever, by deceiving any person, fraudulently or dishonestly induces the person so deceived to deliver any property, or to consent that any person shall retain any property, commits cheating.",
            legal_interpretation="Replaces Sections 415 to 420 of the Indian Penal Code w.e.f. July 1, 2024. Sub-section (4) corresponds to erstwhile Section 420 IPC.",
            ingredients=[
                "1. Fraudulent or dishonest deception of any person.",
                "2. Inducement to deliver property or make/alter valuable security.",
                "3. Section 318(4): Delivery of property or destruction of valuable security.",
            ],
            punishment_or_remedy="Section 318(2): Up to 3 years or fine; Section 318(4): Up to 7 years and fine.",
            related_provisions=["Section 316 BNS (Criminal Breach of Trust)", "Section 336 BNS (Forgery)", "Section 61 BNS (Conspiracy)", "Section 420 IPC"],
            status="In Force",
            effective_date="July 1, 2024",
        ),
        "BNS:316": LegalProvisionResponse(
            act_title="Bharatiya Nyaya Sanhita, 2023",
            act_code="BNS",
            enactment_year=2023,
            jurisdiction="Central",
            section_number="Section 316",
            section_title="Criminal breach of trust",
            what_it_means="Whoever, being in any manner entrusted with property, dishonestly misappropriates or converts to his own use that property, commits criminal breach of trust.",
            legal_interpretation="Replaces Section 405 and 406 IPC. Crucial distinction: in cheating (318 BNS), dishonest intention exists at inception; in criminal breach of trust (316 BNS), entrustment is lawful initially but misappropriation is dishonest subsequently (S.W. Palanitkar).",
            ingredients=[
                "1. Entrustment of property or dominion over property.",
                "2. Dishonest misappropriation, conversion, or unauthorized disposal in violation of legal direction or contract.",
            ],
            punishment_or_remedy="Imprisonment up to 5 years, or fine, or both.",
            related_provisions=["Section 318 BNS", "Section 406 IPC"],
            status="In Force",
            effective_date="July 1, 2024",
        ),
        "BNS:351": LegalProvisionResponse(
            act_title="Bharatiya Nyaya Sanhita, 2023",
            act_code="BNS",
            enactment_year=2023,
            jurisdiction="Central",
            section_number="Section 351",
            section_title="Criminal Intimidation",
            what_it_means="Whoever threatens another with any injury to his person, reputation or property, or to the person or reputation of anyone in whom that person is interested, with intent to cause alarm to that person, commits criminal intimidation.",
            legal_interpretation="Replaces Section 503 and 506 IPC w.e.f. July 1, 2024. Mere vulgar abuse or heated altercation without intent to cause alarm does not constitute criminal intimidation (Vikram Johar v. State of U.P.).",
            ingredients=[
                "1. Threat of injury to person, reputation, or property.",
                "2. Intent to cause alarm, or to cause that person to do an act which he is not legally bound to do.",
            ],
            punishment_or_remedy="Section 351(2): Up to 2 years imprisonment or fine; Section 351(3): If threat is to cause death or grievous hurt, up to 7 years imprisonment or fine.",
            related_provisions=["Section 352 BNS (Intentional Insult)", "Section 506 IPC"],
            status="In Force",
            effective_date="July 1, 2024",
        ),
        "BNS:329": LegalProvisionResponse(
            act_title="Bharatiya Nyaya Sanhita, 2023",
            act_code="BNS",
            enactment_year=2023,
            jurisdiction="Central",
            section_number="Section 329",
            section_title="Criminal trespass and house-trespass",
            what_it_means="Whoever enters into or upon property in the possession of another with intent to commit an offence or to intimidate, insult or annoy any person in possession, or having lawfully entered unlawfully remains there, commits criminal trespass.",
            legal_interpretation="Replaces Section 441, 447, and 448 IPC w.e.f. July 1, 2024. In property disputes, forcible dispossession or encroachment can also trigger civil remedies under the Specific Relief Act (Sections 5 & 6) and preventive proceedings under Section 164 BNSS (formerly Section 145 CrPC).",
            ingredients=[
                "1. Entry into or upon property in possession of another without lawful authority.",
                "2. Intent to commit an offence, or intimidate, insult, or annoy the possessor.",
            ],
            punishment_or_remedy="Imprisonment up to three months, or fine up to five thousand rupees, or both.",
            related_provisions=["Section 331 BNS (Lurking House-trespass)", "Section 6 Specific Relief Act", "Section 164 BNSS"],
            status="In Force",
            effective_date="July 1, 2024",
        ),
        "BNS:100": LegalProvisionResponse(
            act_title="Bharatiya Nyaya Sanhita, 2023",
            act_code="BNS",
            enactment_year=2023,
            jurisdiction="Central",
            section_number="Section 100",
            section_title="Culpable Homicide",
            what_it_means="Whoever causes death by doing an act with the intention of causing death, or with the intention of causing such bodily injury as is likely to cause death, or with the knowledge that he is likely by such act to cause death, commits the offence of culpable homicide.",
            legal_interpretation="Replaces Section 299 IPC w.e.f. July 1, 2024. All murders are culpable homicide, but not all culpable homicides are murder. Punishable under Section 105 BNS (formerly Section 304 IPC).",
            ingredients=[
                "1. Causing of death of a human being.",
                "2. Act done with intention of causing death, or intention to cause bodily injury likely to cause death, or knowledge that the act is likely to cause death.",
            ],
            punishment_or_remedy="Punishable under Section 105 BNS: Imprisonment for life or up to 10 years, and fine.",
            related_provisions=["Section 101 BNS (Murder)", "Section 105 BNS", "Section 106 BNS", "Section 299 IPC"],
            status="In Force",
            effective_date="July 1, 2024",
        ),
        "NI ACT:141": LegalProvisionResponse(
            act_title="Negotiable Instruments Act, 1881",
            act_code="NI Act",
            enactment_year=1881,
            jurisdiction="Central",
            section_number="Section 141",
            section_title="Offences by companies",
            what_it_means="If the person committing an offence under section 138 is a company, every person who, at the time the offence was committed, was in charge of, and was responsible to the company for the conduct of the business of the company, as well as the company, shall be deemed to be guilty of the offence.",
            legal_interpretation="Establishes vicarious criminal liability for directors and key managerial personnel. The company must be arraigned as an accused (Aneeta Hada v. Godfather Travels); specific averments of active day-to-day role are mandatory (SMS Pharmaceuticals).",
            ingredients=[
                "1. Cheque issued by or on behalf of a company or partnership firm.",
                "2. Arraignment of the company as primary corporate accused.",
                "3. Specific averment that named director/signatory was in charge of and responsible for the conduct of company business at the relevant time.",
            ],
            punishment_or_remedy="Deemed liability matching Section 138 penal consequences (imprisonment up to 2 years, or twice cheque fine).",
            related_provisions=["Section 138 NI Act", "Section 142 NI Act"],
            status="In Force",
            effective_date="December 9, 1881",
        ),
    }

    @classmethod
    def get_statute_mapping(cls, act_code: str, section_number: str) -> StatuteMappingResponse | None:
        key = f"{act_code.upper()}:{section_number.upper()}"
        data = cls.STATUTE_MAPPINGS.get(key)
        if not data:
            # Try fuzzy key match
            for k, v in cls.STATUTE_MAPPINGS.items():
                k_act, k_sec = k.split(":")
                if k_act == act_code.upper() and k_sec in section_number.upper():
                    data = v
                    break
        if data:
            return StatuteMappingResponse(**data)
        return None

    @classmethod
    def get_provision(cls, act_code: str, section_number: str) -> LegalProvisionResponse | None:
        key = f"{act_code.upper()}:{section_number.upper()}"
        prov = cls.PROVISIONS.get(key)
        if not prov:
            for k, v in cls.PROVISIONS.items():
                k_act, k_sec = k.split(":")
                if (k_act == act_code.upper() or act_code.upper() in k_act) and (k_sec == section_number.upper() or section_number.upper() in k_sec):
                    return v
        return prov

    @classmethod
    def get_potential_provisions(cls, query_or_concept: str) -> list[PotentialProvisionItem]:
        q = query_or_concept.lower()
        items: list[PotentialProvisionItem] = []

        if any(w in q for w in ["fraud", "dhokhadhadi", "420", "cheating", "chhal"]):
            items = [
                PotentialProvisionItem(
                    act="Bharatiya Nyaya Sanhita, 2023 (BNS)",
                    section="Section 318(4)",
                    title="Cheating and dishonestly inducing delivery of property",
                    why_relevant="Applicable if an individual dishonestly induced another to deliver property or alter valuable security. (Corresponds to erstwhile Section 420 IPC).",
                    statutory_effect="Imprisonment up to 7 years and fine.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart="Section 420, Indian Penal Code, 1860",
                ),
                PotentialProvisionItem(
                    act="Bharatiya Nyaya Sanhita, 2023 (BNS)",
                    section="Section 316",
                    title="Criminal Breach of Trust",
                    why_relevant="May apply if property or money was lawfully entrusted but subsequently dishonestly misappropriated or converted. (Corresponds to erstwhile Section 406 IPC).",
                    statutory_effect="Imprisonment up to 5 years, or fine, or both.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart="Section 406, Indian Penal Code, 1860",
                ),
                PotentialProvisionItem(
                    act="Bharatiya Nyaya Sanhita, 2023 (BNS)",
                    section="Section 336 & Section 338",
                    title="Forgery and Forgery for Purpose of Cheating",
                    why_relevant="May be attracted if fabricated documents, forged signatures, or electronic records were generated to perpetrate the fraud. (Corresponds to Section 465/468 IPC).",
                    statutory_effect="Imprisonment up to 7 years and fine.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart="Section 465 & 468, Indian Penal Code, 1860",
                ),
                PotentialProvisionItem(
                    act="Bharatiya Nyaya Sanhita, 2023 (BNS)",
                    section="Section 61(2)",
                    title="Criminal Conspiracy",
                    why_relevant="May be charged alongside fraud if two or more persons entered into an agreement to carry out an illegal act.",
                    statutory_effect="Penal liability matching the target substantive offence.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart="Section 120B, Indian Penal Code, 1860",
                ),
                PotentialProvisionItem(
                    act="Information Technology Act, 2000",
                    section="Section 66D",
                    title="Cheating by personation by using computer resource",
                    why_relevant="Specifically applicable if the fraud was committed online, via email, social media, or electronic transaction systems.",
                    statutory_effect="Imprisonment up to 3 years and fine up to one lakh rupees.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart=None,
                ),
            ]
        elif any(w in q for w in ["jaan se maar", "maar diya", "hatya", "killing", "murder"]):
            items = [
                PotentialProvisionItem(
                    act="Bharatiya Nyaya Sanhita, 2023 (BNS)",
                    section="Section 101",
                    title="Murder",
                    why_relevant="Applies where death is caused with the intention of causing death or bodily injury objectively sufficient in ordinary course of nature to cause death.",
                    statutory_effect="Punishable under Section 103 BNS with Death or Imprisonment for Life, and fine.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart="Section 300 / Section 302, Indian Penal Code, 1860",
                ),
                PotentialProvisionItem(
                    act="Bharatiya Nyaya Sanhita, 2023 (BNS)",
                    section="Section 100 & Section 105",
                    title="Culpable Homicide not amounting to murder",
                    why_relevant="May apply where death is caused without premeditation, upon grave and sudden provocation, in sudden fight, or with knowledge but without intention to kill.",
                    statutory_effect="Imprisonment for life or up to 10 years, and fine.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart="Section 299 / Section 304, Indian Penal Code, 1860",
                ),
                PotentialProvisionItem(
                    act="Bharatiya Nyaya Sanhita, 2023 (BNS)",
                    section="Section 106",
                    title="Causing death by negligence",
                    why_relevant="Applies where death is caused without mens rea by a rash or negligent act not amounting to culpable homicide (e.g. vehicular accident).",
                    statutory_effect="Imprisonment up to 5 years and fine; or up to 10 years if offender escapes without reporting.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart="Section 304A, Indian Penal Code, 1860",
                ),
                PotentialProvisionItem(
                    act="Bharatiya Nyaya Sanhita, 2023 (BNS)",
                    section="Section 103(2)",
                    title="Mob Lynching / Group Murder",
                    why_relevant="Specifically triggered where murder is committed by five or more persons acting in concert on discriminatory grounds.",
                    statutory_effect="Death or imprisonment for life, and mandatory fine.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart=None,
                ),
            ]
        elif any(w in q for w in ["cheque", "bounce", "dishonour", "138"]):
            items = [
                PotentialProvisionItem(
                    act="Negotiable Instruments Act, 1881",
                    section="Section 138",
                    title="Dishonour of cheque for insufficiency of funds",
                    why_relevant="Primary penal provision for bounced cheques issued towards legally enforceable debt or liability.",
                    statutory_effect="Imprisonment up to 2 years, or fine up to twice the cheque amount, or both.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart=None,
                ),
                PotentialProvisionItem(
                    act="Negotiable Instruments Act, 1881",
                    section="Section 141",
                    title="Offences by Companies",
                    why_relevant="Applies when the bounced cheque is issued by a company or LLP; holds managing directors and signatories vicariously liable.",
                    statutory_effect="Vicarious criminal liability matching Section 138.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart=None,
                ),
                PotentialProvisionItem(
                    act="Negotiable Instruments Act, 1881",
                    section="Section 143A",
                    title="Power to direct interim compensation",
                    why_relevant="Allows the magistrate to order the drawer to deposit up to 20% of the cheque amount as interim relief during trial.",
                    statutory_effect="Interim compensation up to 20% payable within 60 days.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart=None,
                ),
                PotentialProvisionItem(
                    act="Bharatiya Nyaya Sanhita, 2023 (BNS)",
                    section="Section 318(4)",
                    title="Cheating and dishonestly inducing delivery of property",
                    why_relevant="May be charged in conjunction with Section 138 if the accused had no intention of honouring the cheque at the inception of the contract.",
                    statutory_effect="Imprisonment up to 7 years and fine.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart="Section 420, Indian Penal Code, 1860",
                ),
            ]
        elif any(w in q for w in ["dhamki", "threat", "intimidation"]):
            items = [
                PotentialProvisionItem(
                    act="Bharatiya Nyaya Sanhita, 2023 (BNS)",
                    section="Section 351(2)",
                    title="Criminal Intimidation (Simple)",
                    why_relevant="Applies where a person threatens another with injury to person, reputation or property with intent to cause alarm.",
                    statutory_effect="Imprisonment up to 2 years, or fine, or both.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart="Section 506 (Part I), Indian Penal Code, 1860",
                ),
                PotentialProvisionItem(
                    act="Bharatiya Nyaya Sanhita, 2023 (BNS)",
                    section="Section 351(3)",
                    title="Criminal Intimidation (Aggravated - Death or Grievous Hurt)",
                    why_relevant="Applies if the threat was to cause death, grievous hurt, destruction of property by fire, or imputing unchastity to a woman.",
                    statutory_effect="Imprisonment up to 7 years, or fine, or both.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart="Section 506 (Part II), Indian Penal Code, 1860",
                ),
                PotentialProvisionItem(
                    act="Bharatiya Nyaya Sanhita, 2023 (BNS)",
                    section="Section 352",
                    title="Intentional insult with intent to provoke breach of the peace",
                    why_relevant="Frequently invoked where verbal abuse or insults are accompanied by intimidation in public.",
                    statutory_effect="Imprisonment up to 2 years, or fine, or both.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart="Section 504, Indian Penal Code, 1860",
                ),
            ]
        elif any(w in q for w in ["kabja", "property", "trespass", "possession"]):
            items = [
                PotentialProvisionItem(
                    act="Bharatiya Nyaya Sanhita, 2023 (BNS)",
                    section="Section 329",
                    title="Criminal Trespass and House-trespass",
                    why_relevant="Criminal liability for unlawfully entering or remaining upon property with intent to annoy, insult, intimidate, or commit an offence.",
                    statutory_effect="Imprisonment up to 3 months, or fine, or both.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart="Section 441 & 447, Indian Penal Code, 1860",
                ),
                PotentialProvisionItem(
                    act="Specific Relief Act, 1963",
                    section="Section 6",
                    title="Suit by person dispossessed of immovable property",
                    why_relevant="Summary civil remedy allowing a dispossessed person to recover possession without having to establish title, if filed within 6 months.",
                    statutory_effect="Restoration of actual physical possession.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart=None,
                ),
                PotentialProvisionItem(
                    act="Specific Relief Act, 1963",
                    section="Section 5",
                    title="Recovery of specific immovable property",
                    why_relevant="Regular civil title suit for possession based on ownership rights and title deeds.",
                    statutory_effect="Decree for possession and mesne profits.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart=None,
                ),
                PotentialProvisionItem(
                    act="Bharatiya Nagarik Suraksha Sanhita, 2023 (BNSS)",
                    section="Section 164",
                    title="Procedure where dispute concerning land is likely to cause breach of peace",
                    why_relevant="Executive Magistrate powers to attach property and prevent violence between rival claiming parties.",
                    statutory_effect="Magisterial attachment and possession determination.",
                    source_url="https://www.indiacode.nic.in/",
                    is_current_law=True,
                    historical_counterpart="Section 145, Code of Criminal Procedure, 1973",
                ),
            ]

        return items

